Adldap2/Adldap2

docs/GETTING-STARTED.md, src/Adldap/Adldap.php, src/Adldap/Classes/AdldapUsers.php
Creates one new configuration option: the primary user login attribute / identifier (defaults to "samaccountname"), instead of the previously hard-coded options of either GUID, samaccountname, or userPrincipalName. In many places (like the find method) this was simply set as samaccountname, which might not be used in the AD schema in some organizations.
=> Allows user login attribute to be configured

src/Adldap/Adldap.php
*Issue:* User authentication seems to work fine if the credentials are correct. However, when invalid credentials are presented to the `Adldap->authenticate()`, an Exception is thrown. As a side-effect, the rebind is never done, so subsequent auth attempts always fail.
An Exception is probably fine for invalid administrator bind credentials, but if a user mis-types their password, `authenticate()` should probably just return false.
*Fix:* Catch the exception and return false. Also, add the additional not-null check to administrator credentials before rebinding (to support anonymous bind via blank-string administrator credentials).
=> Fix auth with invalid credentials exception

docs/GETTING-STARTED.md, src/Adldap/Adldap.php, src/Adldap/Classes/AdldapUsers.php
Abstracted the standard "objectCategory=person" search filter into a configuration setting, in case it is needed for a particular AD schema (like my organization's weird one!).
The default is still "objectCategory=person".
The config setting is an array in order to separate the attribute and value to better fit with the new search().
=> Added configuration setting for "person" search filter

src/Adldap/Classes/AdldapUsers.php, src/Adldap/Objects/LdapEntry.php
- Add possibility of 'dn' generic attribute for distinguished name in the ldap server response: sometimes the distinguished name is returned as a 'dn' attribute instead of 'distinguished name'. I can only personally test the former, but I don't think this commit should mess up the latter.
- Fix defaultQueryFields assignment location: the default query fields were being assigned too late in the adldapusers->info() method to have the desired effect. Fixed!
Okay, now I'm going to sleep :)
=> Add possibility of 'dn' attribute & fix defaultQueryFields assignment loc

src/Classes/AdldapUsers.php, src/Connections/Ldap.php, src/Exceptions/PasswordPolicyException.php, src/Exceptions/WrongPasswordException.php, src/Interfaces/ConnectionInterface.php
As I mentioned on #18, I implemented a real password change.
The main difference to the `password()` method is that the password won't be set but changed.
Scenario: A user forgot his password and an admin has to reset it.
Solution: `user()->password($username, $newPassword)`
**Note:** In my environment, the password can ignore some password policies! Therefore that's not a good solution if a user just has/wants to change his password.
That's the situation where the new `changePassword()` should be used.
Scenario: A user wants to change his password.
Solution: `user()->changePassword($username, $newPassword, $oldPassword)`
That's how you normally change a password. You have to specify your old and your new password.
To give the user better feedback, I also parse the diagnostic LDAP error. …
=> Real password change

src/Classes/Utilities.php
It took me a while to figure out, why my queries don't work on PHP 5.4.
The workaround method for `ldap_escape()` had a bug, where an empty `$ignore` string is handled incorrectly.
`str_split('')` returns an array with one empty value, so the `foreach` loop loops one time with the empty string, effectively removing all backslashes from the escaped value.
This bugfix checks for an empty string and correctly returns an empty array.
Maybe that's also the cause for issue #26?
=> Correclty handle an empty LDAP escape ignore string

src/Connections/Configuration.php, src/Exceptions/InvalidArgumentException.php
Add possibility to pass an array with options to the Configuration class.
Its cumbersome to set every option separately. Furthermore, the AD settings of an installation are probably stored in a config file, anyway.
Maybe it should also be allowed to pass an array to the constructor of the Adldap Class, which in turn will create the Configuration object? It's an added dependency, though.
=> allow to pass array with configuration options to Configuration class

src/Query/Builder.php, tests/Query/BuilderTest.php
I often search for enabled or disabled objects only.
The filter for that is not that easy to remember. Therefore I think such a little shortcut would be great.
What do you think?
The pull request is not final. I think the filter `(UserAccountControl:1.2.840.113556.1.4.803:=2)` should be extracted somewhere else.
=> Added the ability to search / filter for disabled and enabled objects

src/Connections/Ldap.php
use ldap://hostname:port or ldaps://hostname:port LDAP URL for connection.
reference: https://secure.php.net/manual/en/function.ldap-connect.php
#172
=> fix port setting not work problem

src/Connections/Configuration.php, tests/Connections/ConfigurationTest.php
Now that you guys fixed the port specification we need to set to the default port for SSL connections. This will set the default port to `ConnectionInterface::PORT_SSL` (636) if the configuration array key `port` is not set.
=> Set default port for SSL connections if not specified.

src/Schemas/OpenLDAP.php
In OpenLDAP I believe the default attribute name for Distinguished Name is just dn. This change helps make it possible to find a record, make changes, and save it again. There is a separate issue that may cause breaks so I'll open a different issue for that.
=> Update distinguishedName for OpenLDAP to just dn

src/Schemas/FreeIPA.php
This provides a schema file for FreeIPA support.
FreeIPA is an open source identity provider built on top of Fedora's 389 Directory Server.
The LDAP schema is similar although slightly different to OpenLDAP's, so this is the schema file I have been using for authentication and group membership checks.
=> Initial experimental support for FreeIPA

src/Models/Traits/HasMemberOfTrait.php
Checks for a non-zero value instead of exactly one since recursive searching can return duplicates.
=> Fix User::inGroup() when recursive has dups

src/Schemas/OpenLDAP.php
I was having issues today, as the code defaulted to group.
I'm not 100% sure but I think this is the default objectclass for OpenLDAP.
=> Added Group definition for OpenLDAP

docs/configuration.md, src/Configuration/DomainConfiguration.php, src/Connections/Provider.php, tests/Configuration/DomainConfigurationTest.php, tests/Connections/ProviderTest.php
Many AD deployments use custom CA certificates. If these are not installed in the system, the application needs to dictate where they are, which requires setting `LDAP_OPT_X_TLS_CACERTDIR` or similar. This
commit adds a generic interface for that via the `custom_options` key in `DomainConfiguration`.
All documentation and unit tests have been updated and are passing on my local system.
=> Add support for custom LDAP connection options

src/Query/Builder.php, tests/Query/BuilderTest.php
Not equals functions added to builder.
Functional tests are added for the new implementation of not equals clause.
Function tests added for "equals" clause because them didn't have tests.
**Additionally these functions executed on OpenLDAP server. So results are expected.**
=> Not equals functions added to Builder

composer.json, src/Models/Model.php, src/Search/Factory.php, tests/Models/EntryTest.php
Change deleteAttribute() to use the schema, for delete many attributes for one time
$removal = array(
"memberuid"=>"username",
"apple-group-memberguid"=>"846DE847-D73D-428D-83A8-B95B606C511B"
);
Add mixid for better autocomplete if use OpenLdap schema
=> Fix ldap_mod_del and Add mixid for better autocomplete

src/Models/Attributes/MBString.php, src/Models/Attributes/TSProperty.php, src/Models/Attributes/TSPropertyArray.php, src/Models/User.php, tests/Models/UserTest.php
Decode / Encode userparamters in ActiveDirectory
userparameters is used in ActiveDirectory to set the TerminalServicesInitialProgram and TerminalServicesWorkDirectory properties.
How use :
// get userparameters :
$tsPropArray = $user->getUserParameters();
// update : 
$tsPropArray->set('CtxInitialProgram', 'C:\\prog.exe');
$tsPropArray->set('CtxWorkDirectory', 'C:\\');
$user->setUserParameters($tsPropArray);
=> add userParameters for users

src/Schemas/FreeIPA.php
This breaks the built-in auth in the Laravel module because `getConvertedGuid` never returns a value.
=> FreeIPA GUID is named ipaUniqueId

src/AdldapError.php, src/Connections/ConnectionInterface.php, src/Connections/Ldap.php
If I had this while trying to sort out why #560 wasn't working, my life would have been so much easier!
This adds a new piece of functionality to the Ldap connection to retrieve detailed diagnostic messages from the LDAP server.
`->getLastError()` just returns the basic LDAP error, while `getDetailedError()` will return much more detailed information about what is actually failing.
For instance, if you attempt a `bind()` with a username and password for a User that has an expired password, `getLastError()` will not tell you the exact reason for the login failing, giving you a generic '`Bind Failed`' as the cause. When calling `getDetailedError()`, you will receive a more detailed message from the AD server as to why the login failed (ie, it will tell you that the user's password has …
=> Add getDetailedError, enabling LDAP_OPT_DIAGNOSTIC_MESSAGE

src/Models/ForeignSecurityPrincipal.php, src/Schemas/Schema.php
ForeignSecurityPrincipal is an object use on approved domain, 
when a user of a domain B is member of a group of domain A, a foreignSecurityPrincipal object is create in domain A and contains the attribute memberof.
=> add ForeignSecurityPrincipal class for linked domains

docs/setup.md
Another minor doc tweak. Sorry for nitpicking. I'm upgrading a project from an old version of Adldap2 not having used it before, so the docs are very fresh in my eyes.
=> Correct namespace on BindException examples

composer.json, src/Models/Concerns/HasAttributes.php
Found and fixed a case sensitivity issue where the hasAttribute method would not return true if an attribute is present but with different case.
While setting up a dev instance, I found that the bcmath extension is required but not specified in composer.json.
=> Fixed case sensitivity problem in Model hasAttribute method

composer.json, src/Models/User.php
Since bcmath is only used in only one place, and only in the case of the ActiveDirectory schema, I thought it made sense to eliminate the bcmath dependency.
Please look this over carefully, as I don't have an ActiveDirectory instance to test against. The unit tests pass, but that's all I can say with confidence.
=> remove bcmath dependency

src/Connections/Ldap.php
This PR fixes the scenario when you first bind with a bind user and then try to bind with a regular user.
The library tries to upgrade the same connection twice in this scenario.
How to reproduce:
1. Use 'use_tls' => true in your config and add a bind user
2. execute $provider = $ad->connect(); , this call will succeed
3. Try to auth attempt with another user, ie: $provider->auth()->attempt('userdn', 'password');
The auth()->attempt() call will try to upgrade the connection to TLS again which already is upgraded to TLS and therefor fails. This PR fixes that by only upgrading the same connection once.
=> You can only upgrade the same connection once to TLS

src/Models/User.php
My bad. I didn't notice that I used the `getAttribute` (that will return an array) instead of `getFirstAttribute` (that will return an string like docblock state).
=> Fixed the attribute fetch from schema. It should use getFirstAttribute.

src/Schemas/OpenLDAP.php
When importing from Openldap Account Name would be empty
```
Would you like to display the user(s) to be imported / synchronized? (yes/no) [no]:
> yes
+--------------------------+--------------+-----+
| Name                     | Account Name | UPN |
+--------------------------+--------------+-----+
| Test Person              | test         |     |
```
=> Updatede accountName so it matches OpenLdap

.gitignore, composer.json, phpunit.xml
I've added `ext-json` to composer.json to keep IDEs from complaining that it is not defined in composer.
I've added `composer.lock` to .gitignore file as I do not believe this declaration should only live in your global gitignore.
I've added the `whitelist` option to phpunit.xml as it allows you to run your test-suite locally and see code coverage analysis in your IDE.
=> Small changes to configuration files.

src/Adldap.php, src/Connections/ProviderContainer.php, src/Connections/ProviderContainerException.php, src/Models/Model.php, src/Query/Factory.php, tests/Models/UserTest.php
Refer to [issue #675 ](https://github.com/Adldap2/Adldap2/issues/675).
This adds a `ProviderContainer` that holds all registered connection providers and allows access to them from other parts of the system.
I'm using this to allow for scoped queries on the models.
Needs more test coverage, but I think it's a good starting point.
=> Make models directly querable from static method calls.

src/Models/Model.php
useful attribute, more and more recent versions, less limited than samaccountname
Reading the Schema.php and ActiveDirectory.php, I realize that a lot of 100% ActiveDirectory fields are in the base Schema. Is it related to the history of the package ? Or another reason ?
=> add userPrincipalName dedicated functions

src/Connections/Ldap.php, src/Query/Builder.php, tests/Query/BuilderTest.php
Minimal backport of updated query pagination logic from https://github.com/DirectoryTree/LdapRecord/issues/59.
Adding fuller _controls_ support was considered out of scope as Adldap2 is not receiving new features.
Addresses #760.
=> Minimal LdapRecord pagination backport

src/Schemas/Directory389.php, src/Utilities.php
389 Directory Server doesn't use entryUUID or an attribute of some kind containing a UUID as a unique structural attribute for an object (although version 1.4.4.4 recently introduced entryUUID as per RFC 4530 for openLDAP compatibility). Instead it uses nsUniqueID, which is made out of 4 sequences of 8 hexadecimal digits separated by "-" characters. So, relatively close to a UUID but not identical.
I patched the regex in the isValidGuid() to validate that format as well, althouh it might not be an actual GUID per se.
=> New schema for 389 directory support

src/Schemas/EDirectory.php
A schema for eDirectory, which uses the "guid" attribute as an object unique identifier.
=> New Schema for eDirectory support

src/Query/Builder.php
ldap_get_entries(resource $ldap, resource $result): array|false
If $resource is false, and sent to this function, in php8 it will cause an error " Argument #2 ($result) must be of type resource". So it should avoid this by checking if the $resource is false.
=> fix the data type for php8

.github/workflows/tests.yaml, .gitignore, .travis.yml, composer.json, phpunit.xml, src/Query/Builder.php, src/Query/Processor.php, tests/Models/Attributes/AccountControlTest.php, tests/Models/Attributes/BatchModificationTest.php, tests/Models/GroupTest.php, tests/Models/ModelTest.php, tests/Query/BuilderTest.php, tests/TestCase.php
Hi,
This package got my attention since it was mentionned in the PHP's internals mailing list: https://externals.io/message/116519#116554
This PR makes the tests pass with PHP 7.0 up to PHP 8.0.
There is more work to do to make it fully compatible with PHP 8.1, but before that I wanted to know if you'll accept this changes since you work on LdapRecord now.
=> Fix unit tests

.github/workflows/tests.yaml, phpunit.xml, src/Configuration/DomainConfiguration.php, src/Configuration/Validators/ClassValidator.php, src/Models/Attributes/DistinguishedName.php, src/Models/Model.php, src/Models/User.php, src/Query/Builder.php, src/Query/Paginator.php, src/Query/Processor.php, src/Utilities.php, tests/Query/BuilderTest.php, tests/TestCase.php
All deprecation messages raised during tests execution are now fixed. Tests are green too.
I cannot guarantee there is no deprecation messages still hidden in the code, but we will need static analysis tools to find them.
I've tried to have a minimal impact with this PR to let the behaviour and the interfaces unchanged.
=> Fix tests and deprecation messages in PHP 8.1

src/Models/Group.php
A user that has active directory groups with more than 10k members will not be able to go through all of them.
Issue https://github.com/Adldap2/Adldap2/issues/803
=> Increase range limitation when paginating members
