Adldap2/Adldap2

lib/adLDAP/adLDAP.php

Added the port to the LDAPS URI when connecting.

LDAPS not connecting

---

src/Models/User.php

Added a setter for UserPrincipalName

User attribute setter UserPrincipalName

---

docs/models/USER.md
src/Models/User.php
src/Schemas/ActiveDirectory.php

Hi Steve,
Here are three more methods for user model...

Added expirationDate(), isExpired() and isActive() methods to User model

---

src/Models/User.php

This refers to PR #174. This fix doesn't change the default behavior of the method and should be more friendly in general. Hopefully StyleCI doesn't puke on me again.
Pick one - close the other :)

Alt fix user change password

---

src/Connections/Ldap.php

Reverts Adldap2/Adldap2#178
Just as a reminder to create a 5.3 branch/release in case anyone is handling their own errors. Granted we are on an island and the chance is low.

Revert "make bind function follow spec by returning bool instead of throwing …"

---

src/Models/Traits/HasMemberOfTrait.php

Add recursive flag to inGroup & getGroups methods

---

docs/distinguished-names.md

Syntax error in line 13 & line 21, the correct class name is "DistinguishedName" and not "DinstinguishedName"

Replace DinstinguishedName by DistinguishedName

---

src/Models/Group.php

Was comparing the MemberOf funcionality (in Adldap\Models\Traits\HasMemberOfTrait.php) and thought it would be useful to match the ability to get group members by name in a similar fashion.

Group Member Names

---

src/Models/Group.php

Imported the missing Utilities class for the getMemberNames function.

Imported missing Utilities class.

---

src/Contracts/Schemas/SchemaInterface.php
src/Models/Model.php
src/Schemas/ActiveDirectory.php
src/Schemas/OpenLDAP.php

This basically fixes the same as https://github.com/Adldap2/Adldap2/pull/280 but shouldn't have merge conflicts.

Include fixes for getDistinguishedName for OpenLDAP

---

src/Schemas/OpenLDAP.php

Should be lower case. Forgot to update it before.

Lower cased

---

src/Models/Traits/HasMemberOf.php

Fixed an issue with recursion caused when two groups include each other creating an infinite loop. Added an array to track visited nodes to prevent it from recursing over groups already checked. If you have a better way to do it feel free to change it.

Fixed Recursion Infinite Loop

---

src/Models/User.php
src/Schemas/ActiveDirectory.php
src/Schemas/SchemaInterface.php

Added the missing attributes which mentioned in [this](https://github.com/Adldap2/Adldap2/issues/424) issue.

homeDrive and homeDirectory attributes implemented

---

docs/query-builder.md

I assume this is what you intended?

Typo Fixed

---

docs/models/printer.md

Removed extra getPrinterName()

Get Printer Name listed twice

---

src/Models/User.php
src/Schemas/BaseSchema.php

just adding fax number to schema and getter setter in user model to avoid to use:
`$user->setAttribute('facsimileTelephoneNumber', ##########);`

adding fax

---

src/Models/User.php

Actually, i didn't find a good name for this so feel free to change it if necessary

add option to force password change

---

docs/models/group.md

Add more advanced create example similar to `docs/models/ou.md`

group: Expand create example

---

src/Models/User.php

Added two methods to access the "samaaccountname" attribute from User Model.

Adding a method to Adldap\Models\User.

---

src/Models/Model.php
tests/Models/UserTest.php

Forgot to actually send the method and arguments over to `Builder` :(. Wrote a quick test in `UserTest` to prove it works.
Also refer to issue #675.

Test and fix proxied call

---

src/Query/Builder.php

Update Builder to return null instead of false

---

.gitignore
src/Models/User.php
src/Utilities.php
tests/Models/UserTest.php
tests/TestCase.php
tests/UtilitiesTest.php

Ability to set custom password strategies + Utilities::makeSSHAPassword

---

src/Schemas/OpenLDAP.php

Greetings, 
Please find suggested proposed fix.
Thanks,
Wynand

Changed attribute in OpenLDAP Schema

---

docs/setup.md
src/Connections/Ldap.php
src/Connections/Provider.php
src/Connections/SearchException.php
src/Query/Factory.php
src/Schemas/GSuite.php

Hi,
I've added support for G-Suites Secure LDAP Service.
While at it I added a exception when searches fail because I hit a snag there without any error being shown.

Support for G-Suite Secure LDAP Service

---

docs/models/group.md

Fixed attribute name
